python ./crawling/get_product.py --file_name bottom_leggings
python ./crawling/get_product.py --file_name bottom_denim
python ./crawling/get_product.py --file_name bottom_cotton
python ./crawling/get_product.py --file_name bottom_slacks
python ./crawling/get_product.py --file_name bottom_jogger
python ./crawling/get_product.py --file_name bottom_jumpper
python ./crawling/get_product.py --file_name bottom_short
python ./crawling/get_product.py --file_name bottom_etc
python ./crawling/get_product.py --file_name top_short
python ./crawling/get_product.py --file_name top_sweatshirt
python ./crawling/get_product.py --file_name top_knit
python ./crawling/get_product.py --file_name top_hood
python ./crawling/get_product.py --file_name top_long
python ./crawling/get_product.py --file_name top_shirts
python ./crawling/get_product.py --file_name top_polo
python ./crawling/get_product.py --file_name top_sleeveless
